version: 0.2

phases:
    pre_build:
        commands:
            - echo Logging in to Amazon ECR...
            - echo Build started on `date`
            - echo Installing dependencies...
            - npm install
    build:
        commands:
            - echo Build started on `date`
            - echo Building the Next.js application...
            - npm run build
    post_build:
        commands:
            - echo Build completed on `date`
            - echo Listing build output...
            - ls -la out/

artifacts:
    files:
        - "**/*"
    base-directory: "out"
    name: nextjs-build-$(date +%Y-%m-%d)

cache:
    paths:
        - "node_modules/**/*"
        - ".next/cache/**/*"
