#!/usr/bin/env bash
# Safe Amplify/.env configuration helper (no secrets embedded)
# Usage:
#   ./setup-amplify-env-vars.sh [environment]
# Environments: development (default) | staging | production | test | local
#
# This script writes a .env.* file using values from your current shell
# environment. Ensure you `export` required variables before running.
# .env files are ignored by git via .gitignore.

set -euo pipefail

ENV_NAME="${1:-development}"
case "$ENV_NAME" in
  development) TARGET_FILE=".env.development" ;;
  staging)     TARGET_FILE=".env.staging" ;;
  production)  TARGET_FILE=".env.production" ;;
  test)        TARGET_FILE=".env.test" ;;
  local)       TARGET_FILE=".env.local" ;;
  *) echo "Unknown environment: $ENV_NAME" >&2; exit 1 ;;
esac

# Write .env file with current env values (empty if not set)
cat > "$TARGET_FILE" <<EOF
# Generated by setup-amplify-env-vars.sh for $ENV_NAME
# Do NOT commit this file.

# Database / Auth
DATABASE_URL="${DATABASE_URL:-}"
NEXTAUTH_URL="${NEXTAUTH_URL:-}"
NEXTAUTH_SECRET="${NEXTAUTH_SECRET:-}"
NODE_ENV="${NODE_ENV:-$([ "$ENV_NAME" = production ] && echo production || echo development)}"

# OAuth
GOOGLE_ID="${GOOGLE_ID:-}"
GOOGLE_SECRET="${GOOGLE_SECRET:-}"

# Stripe
NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY="${NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY:-}"
STRIPE_SECRET_KEY="${STRIPE_SECRET_KEY:-}"

# AWS / Amplify (optional)
AWS_REGION="${AWS_REGION:-}"
AMPLIFY_APP_ID="${AMPLIFY_APP_ID:-}"
EOF

echo "✅ Wrote $TARGET_FILE using current shell environment."

echo "➡️  Export variables first, e.g.:"
echo "   export DATABASE_URL=... NEXTAUTH_URL=... NEXTAUTH_SECRET=..."
echo "   export GOOGLE_ID=... GOOGLE_SECRET=..."
echo "   export NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY=... STRIPE_SECRET_KEY=..."
echo "   export AWS_REGION=... AMPLIFY_APP_ID=... (if applicable)"

echo "\nNote: If you deploy with AWS Amplify Console, set the same variables in the Amplify app's Environment variables UI instead of committing them."