# Use postgres/example user/password credentials

services:
    db:
        # Use your custom image from Docker Hub
        image: andriyko1983/events-postgres:latest
        restart: always
        # set shared memory limit when using docker compose
        shm_size: 128mb
        environment:
            POSTGRES_USER: user
            POSTGRES_PASSWORD: password
            POSTGRES_DB: event_db
        ports:
            - "5432:5432"
        volumes:
            # Optional: persist data
            - postgres_data:/var/lib/postgresql/data

    # Optional: Add pgAdmin for database management
    pgadmin:
        image: dpage/pgadmin4:latest
        restart: always
        environment:
            PGADMIN_DEFAULT_EMAIL: shtumpf@gmail.com
            PGADMIN_DEFAULT_PASSWORD: admin
        ports:
            - "8080:80"
        depends_on:
            - db

volumes:
    postgres_data:
